/**
 * Pinned, never-regenerate cross-language interop vectors.
 *
 * Mirror of packages/capsule-publisher-php/tests/StaticFixturesTest.php.
 * Both suites load the same JSON files and assert byte-equal output. The
 * fixtures live in tests/fixtures/static/ and must not be regenerated by
 * any test or CI step — they exist precisely to catch a lockstep refactor
 * of both implementations that the round-trip suite would otherwise miss.
 *
 * Regenerate intentionally with:
 *
 *     rm packages/capsule-publisher-php/tests/fixtures/static/*.json
 *     pnpm --filter @sesamy/capsule-server build
 *     node packages/capsule-server/scripts/generate-static-fixtures.mjs
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { hkdf, fromBase64Url } from "../web-crypto";
import { deriveWrapKey } from "../dca-rotation";
import { buildPublisherJwk } from "../dca-publisher-jwks";
import {
    importIssuerPrivateKey,
    unwrapEcdhP256,
    unwrapRsaOaep,
} from "../dca-wrap";

const FIXTURE_DIR = resolve(
    __dirname,
    "../../../capsule-publisher-php/tests/fixtures/static",
);

function fromHex(s: string): Uint8Array {
    const out = new Uint8Array(s.length / 2);
    for (let i = 0; i < out.length; i++) out[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16);
    return out;
}

function toHex(bytes: Uint8Array): string {
    return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

function readJson<T>(filename: string): T {
    const path = resolve(FIXTURE_DIR, filename);
    if (!existsSync(path)) {
        throw new Error(
            `Static fixture ${filename} missing — generate once with ` +
                `\`node packages/capsule-server/scripts/generate-static-fixtures.mjs\``,
        );
    }
    return JSON.parse(readFileSync(path, "utf-8")) as T;
}

interface HkdfVector {
    ikmHex: string;
    salt: string;
    info: string;
    length: number;
    okmHex: string;
}

interface DeriveWrapKeyVector {
    rotationSecretHex: string;
    scope: string;
    kid: string;
    wrapKeyHex: string;
}

interface PublisherJwkVector {
    inputPublicKeyPem: string;
    inputPrivateKeyPem: string;
    inputKid: string;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    expectedJwk: any;
}

interface EcdhUnwrapVector {
    issuerPrivateKeyPem: string;
    issuerPublicKeyPem: string;
    aad: string;
    wrappedBlob: string;
    expectedPlaintextHex: string;
}

interface RsaUnwrapVector {
    issuerPrivateKeyPem: string;
    issuerPublicKeyPem: string;
    aad: string;
    wrappedBlob: string;
    expectedPlaintextHex: string;
}

const fixturesPresent = existsSync(resolve(FIXTURE_DIR, "hkdf-vectors.json"));

describe.skipIf(!fixturesPresent)("Static known-answer cross-language vectors", () => {
    it("HKDF vectors match for the (salt, info) shapes the publisher uses", async () => {
        const cases = readJson<HkdfVector[]>("hkdf-vectors.json");
        for (const v of cases) {
            const okm = await hkdf(fromHex(v.ikmHex), v.salt, v.info, v.length);
            expect(toHex(okm), `hkdf vector salt=${v.salt} info=${v.info}`).toBe(v.okmHex);
        }
    });

    it("deriveWrapKey vectors match for fixed (rotationSecret, scope, kid)", async () => {
        const cases = readJson<DeriveWrapKeyVector[]>("derive-wrap-key-vectors.json");
        for (const v of cases) {
            const wk = await deriveWrapKey(fromHex(v.rotationSecretHex), v.scope, v.kid);
            expect(toHex(wk), `deriveWrapKey scope=${v.scope} kid=${v.kid}`).toBe(v.wrapKeyHex);
        }
    });

    it("Publisher JWK build is byte-equal for a fixed PEM + kid", async () => {
        const v = readJson<PublisherJwkVector>("publisher-jwk-vector.json");
        const jwk = await buildPublisherJwk({
            publicKeyPem: v.inputPublicKeyPem,
            kid: v.inputKid,
        });
        expect(jwk).toEqual(v.expectedJwk);
    });

    it("ECDH-P256 unwrap recovers the pinned plaintext from the pinned blob", async () => {
        const v = readJson<EcdhUnwrapVector>("ecdh-unwrap-vector.json");
        const priv = await importIssuerPrivateKey(v.issuerPrivateKeyPem, "ECDH-P256");
        const plaintext = await unwrapEcdhP256(
            v.wrappedBlob,
            priv.key,
            new TextEncoder().encode(v.aad),
        );
        expect(toHex(plaintext)).toBe(v.expectedPlaintextHex);
        // belt-and-braces: the blob really is base64url-decodable
        expect(fromBase64Url(v.wrappedBlob).byteLength).toBeGreaterThan(0);
    });

    it("RSA-OAEP unwrap recovers the pinned plaintext from the pinned blob", async () => {
        const v = readJson<RsaUnwrapVector>("rsa-unwrap-vector.json");
        const priv = await importIssuerPrivateKey(v.issuerPrivateKeyPem, "RSA-OAEP");
        const plaintext = await unwrapRsaOaep(
            v.wrappedBlob,
            priv.key,
            new TextEncoder().encode(v.aad),
        );
        expect(toHex(plaintext)).toBe(v.expectedPlaintextHex);
    });
});

describe.skipIf(fixturesPresent)("Static fixtures missing", () => {
    it("explains how to generate them", () => {
        // eslint-disable-next-line no-console
        console.warn(
            "Skipping static-fixture tests. Generate once with:\n" +
                "  pnpm --filter @sesamy/capsule-server build\n" +
                "  node packages/capsule-server/scripts/generate-static-fixtures.mjs",
        );
        expect(true).toBe(true);
    });
});
